# Generated by Django 5.2.17 on 2026-08-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
