# Generated by Django 5.2.17 on 2026-09-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileeditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
