# Generated by Django 5.2.17 on 2026-08-11 04:30

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtoken',
            name='expires_at',
            field=models.DateTimeField(default=attendance.models.default_qr_expiry),
        ),
    ]
