# Generated by Django 5.2.17 on 2026-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_activitylog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
