# Generated by Django 5.2.17 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_seed_class_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='periods',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of continuous timetable periods this single session covers (2 for a merged double period).'),
        ),
    ]
