# Generated by Django 5.2.17 on 2026-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancesession_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('success', 'Success'), ('duplicate', 'Duplicate Attempt'), ('expired_token', 'Expired QR'), ('invalid_token', 'Invalid QR'), ('session_closed', 'Session Closed'), ('new_device', 'New Device'), ('wrong_section', 'Wrong Section')], max_length=20),
        ),
    ]
