# Generated by Django 5.2.17 on 2026-08-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='subject',
            field=models.CharField(default='AI Training', max_length=100),
        ),
    ]
