# Generated by Django 5.1.2 on 2026-09-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(unique=True)),
                ('topics', models.TextField()),
            ],
            options={
                'ordering': ['session_number'],
            },
        ),
    ]
