# Generated by Django 5.2.17 on 2026-08-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
