# Generated by Django 5.2.17 on 2026-08-11 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_activitylog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='attendance.attendancesession'),
        ),
    ]
