# Generated by Django 5.2.17 on 2026-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancesession_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
